server:
  port: 8082
  servlet:
    context-path: /client2
    session:
      cookie:
        name: CLIENT2SESSION
security:
  oauth2:
    client:
      client-id: client2
      client-secret: 123456
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      access-token-uri: http://localhost:9999/uaa/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:9999/uaa/oauth/token_key
